# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none
pr: none


pool:
  vmImage: 'ubuntu-latest'


stages:
- stage: dev
  displayName: Dev stage
  jobs:
  - job: deployVM
    displayName: createOrUpdateVM    
    steps:
    - task: AzureResourceGroupDeployment@2
      displayName: 'Azure Deployment:Create Or Update Resource Group action'
      inputs:
        azureSubscription: 'RMPM (afc11291-9826-46be-b852-70349146ddf8)'
        action: 'Create Or Update Resource Group'
        resourceGroupName: 'ForresterDemo'
        location: 'East US 2'
        templateLocation: 'Linked artifact'
        csmFile: '$(System.DefaultWorkingDirectory)/**/arm-templates/linux-vm-template.json'
        overrideParameters: '-vmName "raivmdemo1" -adminUsername "moala" -adminPasswordOrKey "$(vmPassword)"'
        deploymentMode: 'Incremental'



      